### ISSUE TITLE
Consider using queue interprop as abstraction for queues

### ISSUE THREAD

**Issue by makasim** [LinioIT/queue#4]
Hello!

Please look at https://github.com/queue-interop/queue-interop project. Using interfaces from it allows us reuse some implementations like enqueue, which supports a lot of transports. You can outsource some code

**Comment by klaussilveira** [comment]
This library is biased towards asynchronous job processing, heavily influenced by Ruby's Sidekiq. It doesn't aim to abstract AMQP or any traditional message queue protocol. 

Therefore, I don't think that using interfaces based on JMS would bring any advantages.
